[package]
name = "seams-2"
version = "0.1.0"
edition = "2018"

[dependencies]
wgpu = { git = "https://github.com/gfx-rs/wgpu-rs.git" }
winit = "0.22.2"
imgui = "0.4.0"
futures = "0.3.5"
imgui-winit-support = "0.4.0"
bytemuck = "1.4.0"
read-process-memory = "0.1.2"
nalgebra = "0.22.0"

[build-dependencies]
walkdir = "2.3.1"
